Aritifacts_Id = [
    "vourukasha_glow",
    "nymph_dream",
    "desert_pavilion_chronicle",
    "flower_of_paradise_lost",
    "deepwood_memories",
    "gilded_dreams",
    "vermillion_hereafter",
    "echoes_of_an_offering",
    "hust_of_opulent_dreams",
    "ocean_hued_clam",
    "emblem_of_severed_fate",
    "shimenawa_reminiscence",
    "tenacity_of_the_millelith",
    "archaic_petra",
    "noblesse_oblige",
    "pale_flame",
    "retracing_bolide",
    "thundering_fury",
    "thunder_smoother",
    "crimson_witch",
    "lava_walker",
    "viridescent_venerer",
    "maiden_beloved",
    "heart_of_depth",
    "blizzard_strayer",
    "wanderer_troupe",
    "gladiator_finale",
    "instructor",
    "berserker",
    "bloodstained_chivalry",
    "brave_heart",
    "defender_will",
    "the_exile",
    "gambler",
    "martial_artist",
    "resolution_of_sojourner",
    "scholar",
    "tiny_miracle",
    "prayers_for_destiny_buffer",
    "prayers_for_illumination",
    "prayers_for_wisdom",
    "prayers_to_springtime",
]

Main_Attributes_Id = [
    "hp",
    "hprate",
    "atk",
    "atkrate",
    "defrate",
    "cr",
    "cd",
    "er",
    "em",
    "healing",
    "phydmg",
    "admg",
    "gdmg",
    "edmg",
    "ddmg",
    "hdmg",
    "pdmg",
    "crdmg",
]
Main_Attributes_Value_Range = {
    "hp": (645, 4780),
    "hprate": (0.063, 0.466),
    "atk": (42, 311),
    "atkrate": (0.063, 0.466),
    "defrate": (0.079, 0.583),
    "cr": (0.042, 0.311),
    "cd": (0.084, 0.622),
    "er": (0.07, 0.518),
    "em": (25, 187),
    "healing": (0.048, 0.359),
    "phydmg": (0.079, 0.583),
    "admg": (0.063, 0.466),
    "gdmg": (0.063, 0.466),
    "edmg": (0.063, 0.466),
    "ddmg": (0.063, 0.466),
    "hdmg": (0.063, 0.466),
    "pdmg": (0.063, 0.466),
    "crdmg": (0.063, 0.466),
}

Subattributes_Id = [
    "hp",
    "hprate",
    "atk",
    "atkrate",
    "def",
    "defrate",
    "cr",
    "cd",
    "er",
    "em",
]
SubAttributes_Value_Range = {
    "hp": (167, 299 * 6),
    "hprate": (0.033, 0.058 * 6),
    "atk": (11, 19 * 6),
    "atkrate": (0.033, 0.058 * 6),
    "def": (13, 23 * 6),
    "defrate": (0.041, 0.073 * 6),
    "cr": (0.022, 0.039 * 6),
    "cd": (0.044, 0.078 * 6),
    "er": (0.036, 0.065 * 6),
    "em": (13, 23 * 6),
}
