%YAML 1.2
---
archaic_petra: 悠古的磐岩
berserker: 战狂
blizzard_strayer: 冰风迷途的勇士
bloodstained_chivalry: 染血的骑士道
brave_heart: 勇士之心
crimson_witch: 炽烈的炎之魔女
defender_will: 守护之心
echoes_of_an_offering: 来歆余响
emblem_of_severed_fate: 绝缘之旗印
the_exile: 流放者
gambler: 赌徒
gladiator_finale: 角斗士的终幕礼
heart_of_depth: 沉沦之心
hust_of_opulent_dreams: 华馆梦醒形骸记
instructor: 教官
lava_walker: 渡过烈火的贤人
maiden_beloved: 被怜爱的少女
martial_artist: 武人
noblesse_oblige: 昔日宗室之仪
ocean_hued_clam: 海染砗磲
pale_flame: 苍白之火
prayers_for_destiny_buffer: 祭水之人
prayers_for_illumination: 祭火之人
prayers_for_wisdom: 祭雷之人
prayers_to_springtime: 祭冰之人
resolution_of_sojourner: 行者之心
retracing_bolide: 逆飞的流星
scholar: 学士
shimenawa_reminiscence: 追忆之注连
tenacity_of_the_millelith: 千岩牢固
thundering_fury: 如雷的盛怒
thunder_smoother: 平息鸣雷的尊者
tiny_miracle: 奇迹
vermillion_hereafter: 辰砂往生录
viridescent_venerer: 翠绿之影
wanderer_troupe: 流浪大地的乐团
deepwood_memories: 深林的记忆
gilded_dreams: 饰金之梦
desert_pavilion_chronicle: 沙上楼阁史话
flower_of_paradise_lost: 乐园遗落之花
nymph_dream: 水仙之梦
vourukasha_glow: 花海甘露之光