%YAML 1.2
---
archaic_petra: "archaic_petra"
heart_of_depth: "heart_of_depth"
blizzard_strayer: "blizzard_walker"
retracing_bolide: "retracing_bolide"
noblesse_oblige: "noblesse_oblige"
gladiator_finale: "gladiators_finale"
maiden_beloved: "maiden_beloved"
viridescent_venerer: "viridescent_venerer"
lava_walker: "lavawalker"
crimson_witch: "crimson_witch_of_flames"
thunder_smoother: "thundersoother"
thundering_fury: "thundering_fury"
bloodstained_chivalry: "bloodstained_chivalry"
wanderer_troupe: "wanderers_troupe"
scholar: "scholar"
gambler: "gambler"
tiny_miracle: "tiny_miracle"
martial_artist: "martial_artist"
brave_heart: "brave_heart"
resolution_of_sojourner: "resolution_of_sojourner"
defender_will: "defenders_will"
berserker: "berserker"
instructor: "instructor"
the_exile: "the_exile"
prayers_for_wisdom: "prayers_of_wisdom"
prayers_to_springtime: "prayers_of_springtime"
prayers_for_illumination: "prayers_of_illumination"
prayers_for_destiny_buffer: "prayers_of_destiny"
pale_flame: "pale_flame"
tenacity_of_the_millelith: "tenacity_of_the_millelith"
emblem_of_severed_fate: "seal_of_insulation"
shimenawa_reminiscence: "reminiscence_of_shime"
hust_of_opulent_dreams: "husk_of_opulent_dreams"
ocean_hued_clam: "divine_chorus"
vermillion_hereafter: "vermillion_hereafter"
echoes_of_an_offering: "echoes_of_an_offering"
deepwood_memories: "deepwood_memories"
gilded_dreams: "gilded_dreams"
flower_of_paradise_lost: "flower_of_paradise_list"
desert_pavilion_chronicle: "desert_pavilion_chronicle"
nymph_dream: "nymphs_dream"
vourukasha_glow: "vourukashas_glow"