%YAML 1.2
---
archaic_petra: "archaicPetra"
heart_of_depth: "heartOfDepth"
blizzard_strayer: "blizzardStrayer"
retracing_bolide: "retracingBolide"
noblesse_oblige: "noblesseOblige"
gladiator_finale: "gladiatorFinale"
maiden_beloved: "maidenBeloved"
viridescent_venerer: "viridescentVenerer"
lava_walker: "lavaWalker"
crimson_witch: "crimsonWitch"
thunder_smoother: "thunderSmoother"
thundering_fury: "thunderingFury"
bloodstained_chivalry: "bloodstainedChivalry"
wanderer_troupe: "wandererTroupe"
scholar: "scholar"
gambler: "gambler"
tiny_miracle: "tinyMiracle"
martial_artist: "martialArtist"
brave_heart: "braveHeart"
resolution_of_sojourner: "resolutionOfSojourner"
defender_will: "defenderWill"
berserker: "berserker"
instructor: "instructor"
the_exile: "exile"
prayers_for_wisdom: "prayersForWisdom"
prayers_to_springtime: "prayersToSpringtime"
prayers_for_illumination: "prayersForIllumination"
prayers_for_destiny_buffer: "prayersForDestiny"
pale_flame: "paleFlame"
tenacity_of_the_millelith: "tenacityOfTheMillelith"
emblem_of_severed_fate: "emblemOfSeveredFate"
shimenawa_reminiscence: "shimenawaReminiscence"
hust_of_opulent_dreams: "huskOfOpulentDreams"
ocean_hued_clam: "oceanHuedClam"
vermillion_hereafter: "VermillionHereafter"
echoes_of_an_offering: "EchoesOfAnOffering"
deepwood_memories: "DeepwoodMemories"
gilded_dreams: "GildedDreams"
flower_of_paradise_lost: "FlowerOfParadiseLost"
desert_pavilion_chronicle: "DesertPavilionChronicle"
nymph_dream: "NymphsDream"
vourukasha_glow: "VourukashasGlow"